# Generated by Django 2.1.1 on 2019-04-09 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('like', models.IntegerField(default=0)),
                ('clas', models.TextField()),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=80)),
                ('hours', models.IntegerField(default=0)),
            ],
        ),
    ]
