# Generated by Django 2.1.1 on 2019-04-10 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResRev', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('like', models.IntegerField(default=0)),
                ('restau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResRev.Restaurant')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResRev.Reviewer')),
            ],
        ),
    ]
