# Generated by Django 2.1.1 on 2019-04-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResRev', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='clas',
            field=models.TextField(default='Normal'),
        ),
    ]
